name: Wrong About Everything
favicon: null
layout_spectrum: 0.3860742338001728
typography_spectrum: 0.5783394630998373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.089305266039446
  lightness: 0.8384534399956465
  saturation: 0.8379484256729484
  rhythmicContrast: 0.8456419622525573
purpose: []
